ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

kafka:
  major_version: 3
  minor_version: 6
  patch_version: 2
  scala:
    major_version: 2
    minor_version: 12
  base_path: /usr/local
  download_url: http://apache.rediris.es/kafka
  download_path: /tmp
  download: false
  config:
    port: 9092
    log_dirs: /usr/local/kafka/logs
    log_path: /usr/local/kafka/log
    data_dir: /usr/local/kafka/data
    topic_dirs:
      - "data1"
      - "data2"
    network_threads: 3
    disk_threads: 8
    num_partitions: 3
    so_snd_buff_bytes: 102400
    so_rcv_buff_bytes: 102400
    so_request_max_bytes: 104857600
    data_dir_recovery_threads: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


zookeeper:
  major_version: 3
  minor_version: 9
  patch_version: 2
  base_path: /usr/local
  download_url: http://apache.rediris.es/zookeeper
  download_path: /tmp
  download: false
  config:
    port: 2181
    log_path: /usr/local/apache-zookeeper/log
    data_dir: /usr/local/apache-zookeeper/data
    tick_time: 2000
    init_limit: 5
    sync_limit: 2
  use_internal_zookeeper: false
  # log_path: /var/log/zookeeper
  # data_dir: /var/lib/zookeeper
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


kafka_ui:
  api_version: "0.7.2"
  jmx_port: 9997
  port: 8080
  oracle_java: false
  download: false
  download_url: "https://github.com/provectus/kafka-ui/releases/download"
  # https://github.com/provectus/kafka-ui/releases/download/v0.7.2/kafka-ui-api-v0.7.2.jar


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 13
    minor_version: 0
    patch_version: 2
    download: false


# oracle:
#  version: 8u101
#  installation_path: /usr/java/jdk1.8.0_101
#  build: b13
#  platform: x86_64
#  priority: 100
#  download_mirror: http://download.oracle.com/otn-pub/java/jdk
#  download_cookies: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

