ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"
sudo_user: "gpadmin"
sudo_group: "gpadmin"
sudo_user_pass: "changeme"
sudo_user_home_dir: "/home/{{ sudo_user }}"
domain_name: "jtest.pivotal.io"
