ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

#sudo_user: "jomoon"
#sudo_group: "jomoon"
#sudo_user_pass: "changeme"
#sudo_user_home_dir: "/home/{{ sudo_user }}"
#domain_name: "jtest.pivotal.io"

hadoop:
  user: hadoop
  group: hadoop
  domain: "jtest.pivotal.io"
  hdfs_port: 9000
  base_path: "/home/hadoop"
  download: true
  firewall: false
  download_path: /tmp
  major_version: "3"
  minor_version: "3"
  patch_version: "6"
  bin_type: "tar.gz"
  download_url: "https://dlcdn.apache.org/hadoop/common"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  dashboard:
    port: 9870
  dfs:
    namenode_httpport: 9001
    nameservices: "ha-cluster"
  yarn:
    cluster_id: "my-yarn-cluster"
    resmgr_port: 8040
    resmgr_scheduler_port: 8030
    resmgr_webapp_port: 8088
    resmgr_tracker_port: 8025
    resmgr_admin_port: 8141


kafka:
  major_version: 3
  minor_version: 6
  patch_version: 2
  scala:
    major_version: 2
    minor_version: 12
  base_path: /usr/local
  download_url: http://apache.rediris.es/kafka
  download_path: /tmp
  download: false
  configuration:
    port: 9092
    log_dirs: /usr/local/kafka/logs
    log_path: /usr/local/kafka/log
    data_dir: /usr/local/kafka/data
    topic_dirs:
      - "data1"
      - "data2"
    network_threads: 3
    disk_threads: 8
    num_partitions: 3
    so_snd_buff_bytes: 102400
    so_rcv_buff_bytes: 102400
    so_request_max_bytes: 104857600
    data_dir_recovery_threads: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000
    # log_dirs: /tmp/lib/kafka/kafka-logs
    # data_dir: /var/lib/kafka
    # log_dirs: /usr/local/kafka/logs
    # log_path: /var/log/kafka
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


zookeeper:
  major_version: 3
  minor_version: 9
  patch_version: 2
  base_path: /usr/local
  download_url: http://apache.rediris.es/zookeeper
  download_path: /tmp
  download: false
  configuration:
    port: 2181
    log_path: /usr/local/apache-zookeeper/log
    data_dir: /usr/local/apache-zookeeper/data
    tick_time: 2000
    init_limit: 5
    sync_limit: 2
  use_internal_zookeeper: false
  # log_path: /var/log/zookeeper
  # data_dir: /var/lib/zookeeper
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    pkgs:
      - "java-1.8.0-openjdk"
      - "java-1.8.0-openjdk-devel"
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    pkgs:
      - "java-1.8.0-openjdk"
      - "java-1.8.0-openjdk-devel"


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"
