---
# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'

- name: Install ZooKeeper
  include: install.yml
  tags: install

- name: Uninstall Zookeeper
  include: uninstall.yml
  tags: uninstall
