---
- name: Check OS ( Zookeeper )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, setup, remove


- name: Install ZooKeeper
  import_tasks: install.yml
  tags: setup, install


- name: Uninstall Zookeeper
  import_tasks: uninstall.yml
  tags: remove, uninstall

