- name: Reload and Stop Systemd Service of Zookeeper
  systemd:
    name: "zookeeper"
    enabled: no
    state: stopped
  ignore_errors: true


- name: Delete Config/Log/Data Files for Zookeeper
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "{{ _zookeeper.config.data_dir }}/myid"
    - "{{ zk_application_path }}/conf/zoo.cfg"
    - "{{ _zookeeper.config.log_path }}"
    - "{{ _zookeeper.config.data_dir }}"
    - "{{ _zookeeper.config.data_dir }}"
    - "{{ _zookeeper.base_path }}/apache-zookeeper-{{ zookeeper_version }}"
    - "{{ _zookeeper.base_path }}/apache-zookeeper"
    - "{{ _zookeeper.download_path }}/{{ zk_package_name }}"
    - "/etc/systemd/system/zookeeper.service"


- name: Reload Systemd Services
  systemd:
    daemon_reload: yes
  register: systemd_reloaded
  ignore_errors: true


- name: Remove Zookeeper User
  user: name=zookeeper state=absent
  ignore_errors: true


- name: Remove Zookeeper Group
  group: name=zookeeper state=present
  ignore_errors: true


- name: Remove a Line Including PATH Variablefor Zookeeper
  lineinfile:
    path: "{{ item }}"
    regexp: "^export PATH=(.*)zookeeper(.*)PATH$"
    state: absent
  register: remove_zookeeper_path
  with_items:
    - "/home/{{ _zookeeper.user }}/.bashrc"
    - "/root/.bashrc"

