# Origianal zk_package_name: zookeeper-{{ zookeeper.version }}.tar.gz
- set_fact:
    zk_package_name: apache-zookeeper-{{ zookeeper.version }}.tar.gz
    zk_application_path: "{{ zookeeper.installation_path }}/apache-zookeeper-{{ zookeeper.version }}"

# Stop Zookeeper Services
- name: Reload and Stop Systemd Service of Zookeeper
  systemd:
    name: "zookeeper"
    enabled: no
    state: stopped

#
- name: Delete config/log/data files for Zookeeper
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zookeeper.configuration.data_dir }}/myid"
    - "{{ zk_application_path }}/conf/zoo.cfg"
    - "{{ zookeeper.configuration.log_path }}"
    - "{{ zookeeper.configuration.data_dir }}"
    - "{{ zookeeper.configuration.data_dir }}"
    - "{{ zookeeper.installation_path }}/apache-zookeeper-{{ zookeeper.version }}"
    - "{{ zookeeper.installation_path }}/apache-zookeeper"
    - "{{ package_download_path }}/{{ zk_package_name }}"
    - "/etc/systemd/system/zookeeper.service"

#
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

#
- name: Remove Zookeeper User
  user: name=zookeeper state=absent

#
- name: Remove zookeeper group
  group: name=zookeeper state=present

