---
- hosts: kafka_servers
  remote_user: root
  become: true
  roles:
    - java
    - firewall
    - zookeeper
    - kafka

- hosts: kafka-monitor
  remote_user: root
  become: true
  roles:
    - kafka-ui
