---
- hosts: brokers
  remote_user: root
  become: true
  roles:
    - java
    - firewall
    - zookeeper
    - kafka

- hosts: monitor
  remote_user: root
  become: true
  roles:
    - firewall
    - java
    - kafka-ui
