---
- hosts: kafka_servers
  remote_user: root
  become: true
  roles:
    - java
    - firewall
    - zookeeper
    - kafka

#- hosts: all
#  remote_user: root
#  become: true
#  roles:
#    - kafka-ui
