---
- hosts: monitor
  remote_user: root
  become: true
  roles:
    - kafka-ui
    - firewall
    - java

- hosts: brokers
  remote_user: root
  become: true
  roles:
    - java
    - firewall
    - zookeeper
    - kafka
