---
- hosts: monitor
  become: true
  roles:
    - kafka-ui

- hosts: all
  become: true
  roles:
    - java
    - firewall

- hosts: kafka_brokers
  become: true
  roles:
    - kafka
    - zookeeper

