---
- hosts: monitor
  # remote_user: root
  become: true
  roles:
    - kafka-ui
  #  - firewall
  #  - java

- hosts: kafka_brokers
  # remote_user: root
  become: true
  roles:
    - zookeeper
    - kafka
  #  - java
  #  - firewall

