- name: Set Firewalld Port Policy
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ kafka_ui_port }}"
  when:  inventory_hostname in groups['kafka-monitor']

- name: Check if Java RPM Package is installed
  package_facts:
    manager: "auto"
  when: inventory_hostname in groups['kafka-monitor']

- name: Install Java RPM Package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-17-openjdk
    - java-17-openjdk-devel
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - inventory_hostname in groups['kafka-monitor']
    - install_oracle_java == false

- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jre-17-openjdk/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - inventory_hostname in groups['kafka-monitor']
    - install_oracle_java == false

- name: Copy Oracle JAVA RPM package
  copy: src=jdk-17_linux-x64_bin.rpm dest=/root/jdk-17_linux-x64_bin.rpm mode=0644 owner=root group=root
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int < 8
    - inventory_hostname in groups['kafka-monitor']
    - install_oracle_java == false

- name: Install Oracle Java RPM package
  yum:
    name: /root/jdk-17_linux-x64_bin.rpm
    state: present
    disable_gpg_check: yes
  async: 360
  poll: 5
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int < 8
    - inventory_hostname in groups['kafka-monitor']
    - install_oracle_java == true

- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jdk-17-oracle-x64/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int < 8
    - inventory_hostname in groups['kafka-monitor']
    - install_oracle_java == true

- name: Set Kafka UI Configuration
  template: src=templates/application-kafka-ui.yml dest=/root/application-kafka-ui.yml owner=root group=root mode=644 force=yes
  when: inventory_hostname in groups['kafka-monitor']

- name: Copy API JAR file of Kafka UI
  copy: src=kafka-ui-api-v{{ kafka_ui_api_version }}.jar dest=/root/kafka-ui-api-v{{ kafka_ui_api_version }}.jar mode=0644 owner=root group=root
  when: inventory_hostname in groups['kafka-monitor']

- name: Copy systemd file of Kafka UI
  template: src=kafka-ui.systemd.j2 dest=/etc/systemd/system/kafka-ui.service owner=root group=root mode=644 force=yes
  when: inventory_hostname in groups['kafka-monitor']

- name: Reload and start Kafka UI systemd service
  systemd:
    daemon_reload: yes
    name: kafka-ui
    enabled: yes
    state: started
  register: kafka_ui_systemd_started
  when: inventory_hostname in groups['kafka-monitor']
