- name: Set Firewalld Port Policy
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ kafka_ui_port }}"

- name: Check if Java RPM Package is installed
  package_facts:
    manager: "auto"
  when: inventory_hostname in groups['kafka-monitor']

- name: Install Java RPM Package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-17-openjdk
    - java-17-openjdk-devel
  when: inventory_hostname in groups['kafka-monitor']

- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jre-17-openjdk/bin/java
    priority: -10
  when: inventory_hostname in groups['kafka-monitor']

- name: Set Kafka UI Configuration
  template: src=templates/application-kafka-ui.yml dest=/root/application-kafka-ui.yml owner=root group=root mode=644 force=yes
  when: inventory_hostname in groups['kafka-monitor']

- name: Copy API JAR file of Kafka UI
  copy: src=kafka-ui-api-v0.5.0.jar dest=/root/kafka-ui-api-v0.5.0.jar mode=0644 owner=root group=root
  when: inventory_hostname in groups['kafka-monitor']

#- name: Run Kafka UI
#  become: true
#  become_user: root
#  shell: |
#    java -Dspring.config.additional-location=/root/application-kafka-ui.yml -jar /root/kafka-ui-api-v0.5.0.jar > /var/log/kafka-ui.log 2>&1
#  async: 1000
#  poll: 0
#  when: inventory_hostname in groups['kafka-monitor']

- name: Copy systemd file of Kafka UI
  template: src=kafka-ui.systemd.j2 dest=/etc/systemd/system/kafka-ui.service owner=root group=root mode=644 force=yes

- name: Reload and start Kafka UI systemd service
  systemd:
    daemon_reload: yes
    name: kafka-ui
    enabled: yes
    state: started
  register: kafka_ui_systemd_started
