- name: Check if Java RPM Package is installed
  package_facts:
    manager: "auto"
  when: inventory_hostname in groups['monitor']


- name: Install Java RPM Package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-17-openjdk
    - java-17-openjdk-devel
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - inventory_hostname in groups['monitor']
    - install_oracle_java == false


- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jre-17-openjdk/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - inventory_hostname in groups['monitor']
    - install_oracle_java == false


- name: Copy Oracle JAVA RPM package
  copy: src=jdk-17_linux-x64_bin.rpm dest=/root/jdk-17_linux-x64_bin.rpm mode=0644 owner=root group=root
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - inventory_hostname in groups['monitor']
    - install_oracle_java == true


- name: Install Oracle Java RPM package
  yum:
    name: /root/jdk-17_linux-x64_bin.rpm
    state: present
    disable_gpg_check: yes
  async: 360
  poll: 5
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - inventory_hostname in groups['monitor']
    - install_oracle_java == true


- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jdk-17-oracle-x64/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - inventory_hostname in groups['monitor']
    - install_oracle_java == true
