- name: Set Kafka UI Configuration
  template: src=templates/application-kafka-ui.yml dest=/root/application-kafka-ui.yml owner=root group=root mode=644 force=yes
  when: inventory_hostname in groups['monitor']


- name: Copy API JAR file of Kafka UI
  copy: src=kafka-ui-api-v{{ kafka_ui_api_version }}.jar dest=/root/kafka-ui-api-v{{ kafka_ui_api_version }}.jar mode=0644 owner=root group=root
  when: inventory_hostname in groups['monitor']


- name: Copy Systemd File of Kafka UI
  template: src=kafka-ui.systemd.j2 dest=/etc/systemd/system/kafka-ui.service owner=root group=root mode=644 force=yes
  when: inventory_hostname in groups['monitor']


- name: Reload and Start Kafka UI Systemd Service
  become_user: root
  systemd:
    daemon_reload: yes
    name: kafka-ui
    enabled: yes
    state: started
  register: kafka_ui_systemd_started
  when: inventory_hostname in groups['monitor']

