---
- name: Stop and Disable Kafka UI Systemd Service
  systemd:
    name: kafka-ui
    enabled: no
    state: stopped
  register: stop_kafka_ui_service
  ignore_errors: yes


- name: Remove Config and Jar Files of Kafka UI
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: yes
  with_items:
    - "/var/log/kafka-ui.log"
    - "/root/application-kafka-ui.yml"
    - "/root/kafka-ui-api-v{{ _kafka_ui.api_version }}.jar"
    - "/etc/systemd/system/kafka-ui.service"


- name: Disable Firewalld Port Policy for Kafak UI
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: disabled
    immediate: yes
  ignore_errors: yes
  with_items:
    - "{{ _kafka_ui.port }}"


- name: Reload Systemd Services
  systemd:
    daemon_reload: yes
  register: systemd_reloaded
  ignore_errors: yes

