- name: Start Kafka
  service: name=kafka state=started enabled=yes


- name: Stop Kafka
  service: name=kafka state=stopped enabled=yes


- name: Restart Kafka
  service: name=kafka state=restarted enabled=yes


- name: Start Zookeeper
  service: name=zookeeper state=started enabled=yes


- name: Stop Zookeeper
  service: name=zookeeper state=stopped enabled=yes


- name: Restart Zookeeper
  service: name=zookeeper state=restarted enabled=yes
