---
- name: Create Zookeeper Group
  group: name=zookeeper state=present
  when: ( _zookeeper.use_internal_zookeeper )


- name: Create Zookeeper User
  user: name=zookeeper group=zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Set Zookeeper Data Directory
  file: path={{ _zookeeper.config.data_dir }} state=directory owner=zookeeper group=zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Set Zookeeper Log Directory
  file: path={{ _zookeeper.config.log_path }} state=directory owner=zookeeper group=zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Set Zookeeper Data Directory
  file: path={{ _zookeeper.config.data_dir }} state=directory owner=zookeeper group=zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Set Internal Zookeeper Configuration
  template: src=templates/zookeeper.config.j2 dest={{ kafka_application_path }}/config/zookeeper.properties force=yes
  notify: Restart Zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Set Zookeeper myid Configuration
  template: src=templates/zookeeper.myid.j2 dest={{ _zookeeper.config.data_dir }}/myid owner=zookeeper group=zookeeper mode=644 force=yes
  notify: Restart Zookeeper
  when: ( _zookeeper.use_internal_zookeeper )


- name: Replace Data Directory of Zookeeper Properties
  replace:
    path: "{{ _zookeeper.base_path }}/kafka/config/zookeeper.properties"
    regexp: "^(.*)dataDir=(.*)$"
    replace: "dataDir={{ _zookeeper.config.data_dir }}"
    backup: yes
  when: ( _zookeeper.use_internal_zookeeper )


- name: Copy Systemd Configuration of Zookeeper into /etc/systemd/system
  template: src=zookeeper.systemd.j2 dest=/etc/systemd/system/zookeeper.service owner=root group=root mode=644 force=yes
  when: ( _zookeeper.use_internal_zookeeper )


- name: Reload and Start Systemd Service of Zookeeper
  systemd:
    daemon_reload: yes
    name: zookeeper
    enabled: yes
    state: started
  register: start_zookeeper
  until: start_zookeeper is succeeded
  retries: 20
  delay: 20
  when: ( _zookeeper.use_internal_zookeeper )

