---
# For now fail if it's not a Red Hat based system
- name: Check OS ( Kafka )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Install Internal Zookeeper
  import_tasks: install-internal-zookeeper.yml
  tags: install
  when: ( zookeeper.use_internal_zookeeper )


- name: Install Kafka
  import_tasks: install-kafka.yml
  tags: install


- name: Uninstall Kafka
  import_tasks: uninstall.yml
  tags: uninstall

