---
- name: Reload and Stop Systemd Service of Kafka
  become: true
  systemd:
    name: "kafka"
    enabled: no
    state: stopped


- name: Reload and Stop Systemd Service of Internal Zookeeper
  become: true
  systemd:
    name: "zookeeper"
    enabled: no
    state: stopped
  when: ( zookeeper.use_internal_zookeeper )


- name: Delete config/log/data Files for Kafka
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kafka_application_path }}/config/server.properties"
    - "{{ kafka.configuration.log_dirs }}"
    - "{{ kafka.configuration.log_path }}"
    - "{{ kafka.configuration.data_dir }}"
    - "{{ kafka.base_path }}/kafka_{{ scala_version }}-{{ kafka_version }}"
    - "{{ kafka.base_path }}/kafka"
    - "{{ kafka.download_path }}/{{ kafka_package_name }}"
    - "/etc/systemd/system/kafka.service"


- name: Delete config/log/data Files for Internal Zookeeper
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zookeeper.base_path }}/kafka/config/zookeeper.properties"
    - "{{ zookeeper.configuration.data_dir }}/myid"
    - "{{ zookeeper.configuration.data_dir }}"
    - "{{ zookeeper.configuration.log_path }}"
    - "{{ zookeeper.configuration.data_dir }}"
    - "/etc/systemd/system/zookeeper.service"
  when: ( zookeeper.use_internal_zookeeper )


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes


- name: Delete Zookeeper Group
  group: name=zookeeper state=absent
  when: ( zookeeper.use_internal_zookeeper )


- name: Delete Zookeeper User
  user: name=zookeeper state=absent
  when: ( zookeeper.use_internal_zookeeper )


- name: Delete Kafka Group
  group: name=kafka state=present


- name: Delete Kafka User
  user: name=kafka state=present

