#
- set_fact:
    kafka_package_name: kafka_{{ kafka.scala_version }}-{{ kafka.version }}.tgz
    kafka_application_path: "{{ kafka.installation_path }}/kafka_{{ kafka.scala_version }}-{{ kafka.version }}"

# Stop Services for Kafka
- name: Reload and Stop Systemd Service of Kafka
  become: true
  systemd:
    name: "kafka"
    enabled: no
    state: stopped

# Stop Internal Zookeeper Services
- name: Reload and Stop Systemd Service of Internal Zookeeper
  become: true
  systemd:
    name: "zookeeper"
    enabled: no
    state: stopped
  when: ( zookeeper.use_internal_zookeeper )

#
- name: Delete config/log/data files for Kafka
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kafka_application_path }}/config/server.properties"
    - "{{ kafka.configuration.log_dirs }}"
    - "{{ kafka.configuration.log_path }}"
    - "{{ kafka.configuration.data_dir }}"
    - "{{ kafka.installation_path }}/kafka_{{ kafka.scala_version }}-{{ kafka.version }}"
    - "{{ kafka.installation_path }}/kafka"
    - "{{ package_download_path }}/{{ kafka_package_name }}"
    - "/etc/systemd/system/kafka.service"

#
- name: Delete config/log/data files for Internal Zookeeper
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zookeeper.installation_path }}/kafka/config/zookeeper.properties"
    - "{{ zookeeper.configuration.data_dir }}/myid"
    - "{{ zookeeper.configuration.data_dir }}"
    - "{{ zookeeper.configuration.log_path }}"
    - "{{ zookeeper.configuration.data_dir }}"
    - "/etc/systemd/system/zookeeper.service"
  when: ( zookeeper.use_internal_zookeeper )

#
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

#
- name: Delete Zookeeper Group
  group: name=zookeeper state=absent
  when: ( zookeeper.use_internal_zookeeper )

#
- name: Delete Zookeeper User
  user: name=zookeeper state=absent
  when: ( zookeeper.use_internal_zookeeper )

#
- name: Delete Kafka Group
  group: name=kafka state=present

#
- name: Delete Kafka User
  user: name=kafka state=present
