- name: Enable and Start Firewalld
  systemd:
    name: firewalld
    enabled: true
    state: started


- name: Set Firewalld Port Policy
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "9092" # {{ kafka.configuration.port }}"
    - "2181" # {{ zookeeper.configuration.port }}"
    - "8088" # {{ webview.configuration.port }}"
    - "2888" # Quorum?
    - "3888" # Quorum?
  notify: Restart Firewall


#- name: Disable and Stop Firewalld
#  service: name=firewalld enabled=no state=stopped
#  ignore_errors: yes

