- name: Enable and Start Firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Set Firewalld Port Policy
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ kafka.configuration.port }}"
    - "{{ zookeeper.configuration.port }}"
    - "{{ webview.configuration.port }}"
  notify: firewall restart

- name: Enable and Stop Firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: stopped
