- name: Disable Firewalld Port Policy
  firewalld: port={{ item }}/tcp permanent=true state=disabled immediate=yes
  with_items:
    - "9092" # {{ kafka.configuration.port }}"
    - "2181" # {{ zookeeper.configuration.port }}"
    - "8088" # {{ webview.configuration.port }}"
    - "2888" # Quorum?
    - "3888" # Quorum?
  ignore_errors: yes
  notify: Restart Firewall


- name: Disable and Stop Firewalld
  service: name=firewalld enabled=no state=stopped
  ignore_errors: yes

