#- set_fact:
#    jdk_package_name: jdk-{{ java.version }}-{{ java.platform }}.rpm
#  tags: 
#    - java 
#    - java_installation

#
- name: Check if Java RPM Package is installed
  package_facts:
    manager: "auto"


- name: Install Java RPM Package for RHEL/CentOS/Rocky 8 and higher versions
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-17-openjdk
    - java-17-openjdk-devel
    - tar
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - install_oracle_java == false


- name: Install Java RPM Package for RHEL/CentOS/Rocky 7 and lower versions
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - java-11-openjdk
    - java-11-openjdk-devel
    - tar
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int < 8
    - install_oracle_java == false


- name: Copy Oracle JAVA RPM package
  copy:
    src: jdk-{{ oracle_java_version }}_linux-x64_bin.rpm
    dest: /root/jdk-{{ oracle_java_version }}_linux-x64_bin.rpm
    mode: 0644
    owner: root
    group: root
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - install_oracle_java == true


- name: Install Oracle Java RPM package
  yum:
    name: /root/jdk-{{ oracle_java_version }}_linux-x64_bin.rpm
    state: present
    disable_gpg_check: yes
  async: 360
  poll: 5
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - install_oracle_java == true


- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jre-17-openjdk/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int >= 8
    - install_oracle_java == false


- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int < 8
    - install_oracle_java == false


- name: Correct Java Version Selected
  alternatives:
    link: /usr/bin/java
    name: java
    path: /usr/java/jdk-{{ oracle_java_version }}/bin/java
    priority: -10
  when:
    - hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8
    - install_oracle_java == true
  #  path: /usr/lib/jvm/jdk-{{ oracle_java_version }}-oracle-x64/bin/java


- name: Copy Java Home Script
  template: src=java_home.sh dest=/etc/profile.d


- name: Set Java Home Script
  shell: source /etc/profile.d/java_home.sh


- name: Get Java Version
  shell: java -version
  register: javaVersion


- name: Set Java Version Fact
  set_fact:
    java_version: "{{ javaVersion.stdout_lines }}"

- name: debug
  debug: var=java_version

#- name: download jdk package if not downloaded
#  get_url: url={{ java.download_mirror }}/{{ java.version }}-{{ java.build }}/{{ jdk_package_name }} dest={{ package_download_path }} headers={{ java.download_cookies }}
#  when: not jdk_package_exists.stat.exists 
#  tags:
#    - java 
#    - java_installation

#- name: make java system alternative
#  priority parameter its supported in Ansible > 2.2
#  alternatives: name=java path={{ java.installation_path }}/bin/java link=/usr/bin/java
#  tags: 
#    - java 
#    - java_installation

