package_download_path : "/tmp"
kafka:
  version: 3.3.1
  scala_version: 2.13
  installation_path: /usr/local
  download_mirror: http://apache.rediris.es/kafka
  configuration:
    port: 9092
    data_dir: /var/lib/kafka
    log_dirs: /tmp/lib/kafka/kafka-logs
    log_path: /var/log/kafka
    network_threads: 3
    disk_threads: 8
    num_partitions: 3
    so_snd_buff_bytes: 102400
    so_rcv_buff_bytes: 102400
    so_request_max_bytes: 104857600
    data_dir_recovery_threads: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000
  use_internal_zookeeper: false
#  use_internal_zookeeper: 1
